version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-cu0kms3qf0us73b0fhhg-a.frankfurt-postgres.render.com
      - DB_PORT=5432
      - DB_DATABASE=bookstore_u02x
      - DB_USERNAME=root
      - DB_PASSWORD=cpztKE013AzPd5Za3a0Mb7BDqTTY3MdG
      - DB_SSLMODE=require
    ports:
      - "8080:8080"  # Utiliser un port différent pour éviter les conflits
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
volumes:
  - .:/var/www/html