version: '3.8'

services:
  # Service pour l'application Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-cu0kms3qf0us73b0fhhg-a.frankfurt-postgres.render.com  # Remplacez par l'hôte de Render
      - DB_PORT=5432
      - DB_DATABASE=bookstore_u02x  # Remplacez par le nom de la base de données
      - DB_USERNAME=root  # Remplacez par l'utilisateur de la base de données
      - DB_PASSWORD=cpztKE013AzPd5Za3a0Mb7BDqTTY3MdG  # Remplacez par le mot de passe de la base de données
      - DB_SSLMODE=require
    ports:
      - "8000:80"
    networks:
      - laravel_network

# Réseau pour connecter les services
networks:
  laravel_network:
    driver: bridge